FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    g++ \
    libcurl4-openssl-dev \
    ca-certificates \
    qtbase5-dev qt5-qmake \ 
    && update-ca-certificates

WORKDIR /app

COPY . .

RUN cmake -S . -B build && cmake --build build

CMD ["./build/frontend/frontend"]